### ISSUE TITLE
Encoder not registering speed

### ISSUE THREAD

**Issue by Zggis** [ukmars/motorlab#2]
Hi,

I am trying to use this project with the following setup:
Encoder - https://www.pololu.com/product/4760
Motor - https://www.pololu.com/product/3072
Microcontroller (Arduino Uno based) - https://wiki.dfrobot.com/Romeo_BLE_mini_V2.0_SKU_DFR0351
Battery - 2S 7.4V 30C LiPo

```
//config.h
const int SERIAL_TX = 0;
const int SERIAL_RX = 1;
const int ENCODER_CLK = 3;
const int ENCODER_DIR = 8;
const int MOTOR_DIR = 7;
const int MOTOR_PWM = 6;
const int BATTERY_ADC_PIN = A7;
const int BATTERY_CHANNEL = 7;
//config-motorlab.h
const float GEAR_RATIO = 29.86;
const float ENCODER_PULSES = 12.0;
```

It seems like whatever I do, executing a STEP command, clicking the 'ID' or 'MOVE' buttons in the dashboard the console output seems to indicate speed is not being registered, seems to stay around 0 with the occasional jump to some arbitrary value (i think 62), than back down to 0. The bottom graph on the dashboard seems to show the same, with a mostly flat line with tiny peaks and valleys.

I have tried changing and switching the encoder pins and the ENCODER_POLARITY but the result always seems to be the same. My encoder does not have a CLK pin, but I didn't think that should matter for this application and figured either pin could be used as the CLK pin. I looked closely at [encoder_input_change](https://github.com/ukmars/motorlab/blob/main/ukmarsbot-motorlab/src/encoders.h#L122-L131) and tried making some modifications to it but no luck.

NOTE: I have not connected my battery in any way to A7 yet, I have been struggling to find a good guide / example of this online. I don't think that would be causing the above issue, but worth noting. If you have a good link that demonstrates how to do this that would be much appreciated.

**Comment by micromouseonline** [comment]
The encoder input **must** get both phases. Otherwise any counting will just bounce up and down by one count.

The project is only intended to work with the UKMARSBOT hardware or equivalent. the most significant part is that the encoder signals pass though an XOR gate to generate the CLK input. See:

https://github.com/ukmars/ukmarsbot/blob/master/hardware/mainboard/version-1.3/ukmarsbot-mainboard-V1.3-alpha-schematic.pdf

Everything depends on getting proper counts from the encoders so just have a test loop that prints the encoder counters to the serial monitor and get that working so that you get the correct outputs before you try anything ese.

It would be possible to re-write the encoder input code if you wanted to do without the XOR gate but I do not have a known good example for this. Possibly something like this?

```
  static bool lastEncoderB;
  if (lastEncoderB ^ digitalReadFast(ENCODER_RIGHT_A)) {
    encoder_right_counter++;
  } else {
    encoder_right_counter--;
  }
  lastEncoderB = digitalReadFast(ENCODER_RIGHT_B);
```

**Comment by Zggis** [comment]
Thank you. Your code pretty much worked as is, here is the final solution I used in encoders.h

` 
void encoder_input_change() {
  static bool lastEncoderB;
  if (lastEncoderB ^ digitalRead(ENCODER_CLK)) {
    m_right_counter += ENCODER_POLARITY;
  } else {
    m_right_counter -= ENCODER_POLARITY;
  }
  lastEncoderB = digitalRead(ENCODER_DIR);
}
`

Appreciate all you do, I have enjoyed your presentations.
